<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Stealc.Agent</RootNamespace>
    <AssemblyName>stealc</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../stealc-stealer.Grabber/stealc-stealer.Grabber.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
